# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Orchestrate or schedule a set of jobs
jobs:
  print_hello:
    environment:
      CODE: Hello
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo $CODE
  print_world:
    environment:
      CODE: World
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo $CODE
workflows:
  # Name the workflow "welcome1"
    jobs:
      - print_hello
      - print_world:
          requires:
            - print_hello
